language: cpp

os:
  - linux
  - osx

# Set Xcode version to 10.1 (default is 9.4)
osx_image: xcode10.1
  
compiler:
  - gcc
  - clang

sudo: required
dist: xenial

before_install:
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq valgrind; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew update; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install valgrind; fi"

before_script:
  - mkdir build
  - cd build
  - cmake ../prj/cmake -DCMAKE_BUILD_TYPE=Debug -DSIMD_AVX512=OFF -DCMAKE_CXX_FLAGS=-fsanitize=memory

script: 
  - make
  - cp -R ../data ../../
  - cat /proc/cpuinfo
  - ./Test
  - cd ../test
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-fsanitize=memory
  - make
  - valgrind --track-origins=yes ./UseFaceDetection
