language: cpp

os:
  - linux
  - osx

# Set Xcode version to 10.1 (default is 9.4)
osx_image: xcode10.1
  
compiler:
  - gcc
  - clang

sudo: required
dist: xenial

before_script:
  - mkdir build
  - cd build
  - cmake ../s-trinh/Simd/prj/cmake -DCMAKE_BUILD_TYPE=Debug -DSIMD_AVX512=OFF

script: 
  - make
  - cp -R ../s-trinh/Simd/data ../../
  - ./Test
